### ISSUE TITLE
create release zones around a shape section function fails to return particle positions with expected coordinates

### ISSUE THREAD

**Issue by mollyjames2** [pmlmodelling/pylag#73]
1.	The epsg_code parameter in that function isn't propagated to the function used to perform the coordinate transformation, meaning the code will always be inferred from the start index.
	2.	The function should make it possible to return particle positions in lat-lon coordinates, rather than transformed UTM coordinates.

**Comment by jimc101** [comment]
I propose to address the two points separately. The first point refers to a bug - epsg code should be used a be common to each release zone created. The second point is valid, but I think it can be addressed by improving the API and functionality of the ReleaseZone class. I will enter this as a separate issue, so that changes to ReleaseZone can be made in one go.

**Comment by jimc101** [comment]
Second point now covered in Issue #83.
